Throwing destructors need noexcept(false)
h5md/h5xx pull request #1
Opened 2018-07-30 12:54 UTC by mkuron

Recent compilers (e.g. GCC 6 and higher) warn when destructors throw exceptions.
```
/builds/espressomd/docker/espresso/libs/h5xx/h5xx/dataset/dataset.hpp: In destructor 'h5xx::dataset::~dataset()':
/builds/espressomd/docker/espresso/libs/h5xx/h5xx/dataset/dataset.hpp:153:98: error: throw will always call terminate() [-Werror=terminate]
             throw error("closing h5xx::dataset with ID " + boost::lexical_cast<std::string>(hid_));
```
Since C++11, destructors default to `noexcept`, so we need to explicitly mark the destructors as throwing.

2018-07-30 21:47 UTC, hmenke requested changes
You should replace the destructors by throwing `close()` methods, so that that the user can handle exceptions.  If the destructor throws you have no way to retry.  That is to say that the following design would be preferrable
```cpp
inline dataset::close()
{
    if (hid_ >= 0) {
        if(H5Dclose(hid_) < 0){
            throw error("closing h5xx::dataset with ID " + std::to_string(hid_));
        }
        hid_ = -1;
    }
}

inline dataset::~dataset() noexcept(false)
{
    this->close();
}
```
That is also the way the standard library handles possibly throwing destructors, see e.g. `std::fstream`.

2018-07-31 11:04 UTC, hmenke reviewed
The README states that this library works with C++98.  However, `noexcept` was only introduced in C++11.  You might have to replace `noexcept(false)` by `throw(error)`.  But I don't see any reason to keep C++98 compatibility.  This ancient standard should go extinct already.

2018-07-31 14:20 UTC, mkuron commented
@hmenke, thanks. I decided to use `__cplusplus >= 201103L` instead as `throw(error)` will be incompatible with C++20.

2018-08-13 21:54 UTC, fhoefling commented
Some amendments:

1) I have to weaken my statement about the `close` method. We have (and need) default constructors, so instances of invalid descriptors (hid = -1) can exist. On the other hand, we don't have an `open` method. So by symmetry, we don't need it. Adding it to some extend changes the API design. Concerning exception throwing: whether the destructor throws directly or calls a throwing method doesn't make any difference.

2) I didn't read carefully the whole thread. @hmenke's comment that the caller should "retry" closing is interesting, but I don't see in practice why the caller should call `close` again after a failure. (In this case, the HDF5 library appears to be in an inconsistent state. Can this be repaired from outside?) It might be different for a file handle, where another process may block something. Is there a similar situation for HDF5?

3) C++11 definitely needs to be supported. I consider this a major change (from the user's perspective), which should be communicated clearly. Suggestion: move the current C++98 state to a side branch (which will be developed further or not, depending on the needs) and fully switch master to C++11. This would imply a number of changes to the code (which appear not so difficult), e.g., switching to properly deleted copy constructors.

2018-08-13 23:10 UTC, hmenke commented
The problem with throwing destructors is that you have no way to catch this exception and if another exception is thrown somewhere else, you'll have two exception in flight which will automatically invoke `std::terminate`.

Consider the case where you have a `std::vector<dataset>` with say 10 elements.  When the vector goes out of scope the destructors for all 10 datasets are run.  If the first one throws, the others still need to be destroyed, but if another one throws as well your application will crash.

This is why objects like `std::fstream` provide a `close()` method.  You can iterate over the vector and call the `close()` method on each object individually and handle (or ignore) exceptions one by one, ensuring that there is always only one exception at a time.

On the other hand you mention that if closing fails, the HDF5 library will be in an inconsistent state, so why do you throw an exception in the first place rather than just `assert`ing?  If a certain event is not recoverable, there is no point to continue execution and the application should immediately log and halt.

2018-08-14 08:36 UTC, fhoefling commented
I see your point, and I admit that I didn't think about closing a  
collection of datasets one-by-one before destroying the whole container.  
(Obviously, I've never worked with collections of streams.)

Fortunately, this pattern is already possible with the present interface  
of h5xx, by assigning a default constructed object to each item. So I tend  
to say that there is no need of blowing up the interface by adding `close`  
methods (in the absence of `open`).

What do you mean with "asserting"? A special kind of exception? Assertions  
are meant for debugging purposes (catch my coding faults), exceptions are  
for runtime errors. It seems that I'm not alone with this view:

https://stackoverflow.com/questions/409794/exception-vs-assert
https://softwareengineering.stackexchange.com/questions/15515/using-assertions-versus-throwing-exceptions
http://cpp-today.blogspot.com/2010/02/asserts-vs-exceptions.html

2018-08-14 11:39 UTC, fhoefling commented
@hmenke I didn't see your edit, thanks for the reference to Scott Meyers book.

The ultimate suggestion there is to swallow the exception, log the case, and call `std::abort`. However, we have no means of logging. So I'm curious about an alternative to emitting the error message as the exception string.

The second advice of "item 8" is fulfilled. As I described above, we have an equivalent to `close`.

2020-09-02 07:38 UTC, closed without merging